#!/bin/bash
echo Building testprint...
fpc testprint.pp -TWIN32 -Sc -S2 -Oa -XX -O3 -CpPENTIUMM -CfSSE2 -Ooregvar -Oouncertain -Oostackframe -Oopeephole -Ooasmcse -Ooloopunroll -Ootailrec
echo Cleaning...
rm *.o
